name: Deploy to Azure Container App

on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  IMAGE_NAME: projetdevopsg1 
  RESOURCE_GROUP: ADDE92-CTP
  CONTAINER_APP_NAME: containerappg1  
  CONTAINER_APP_ENV: Envg1
  LOCATION: westeurope  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Azure Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}  
        password: ${{ secrets.REGISTRY_PASSWORD }}  

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - name : make env container app
      run: |
       az containerapp env create -n ${{env.CONTAINER_APP_ENV}} -g ${{env.RESOURCE_GROUP}} --location ${{env.LOCATION}}
    - name: Deploy to Azure Container App
      run: |
        az containerapp create -n ${{ env.CONTAINER_APP_NAME }} -g ${{ env.RESOURCE_GROUP }} --image ${{ env.IMAGE_NAME }}:latest --environment ${{ env.CONTAINER_APP_ENV }} --ingress external --target-port 80